### ISSUE TITLE
XEPs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [redsolution/xabber-web#11]
It is possible to have a XEPs support page with version?

Examples:
- https://metronome.im/supported-xeps-list
- https://trac.gajim.org/wiki/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by oxoWrk** [comment]
[Supported XEPs List](https://github.com/redsolution/xabber-web/wiki/Supported-XEPs-List)

**Comment by Neustradamus** [comment]
No, there are not versions!
Time to look and update if it is not the last XEPs (and RFCs of course)

**Comment by andrewnenakhov** [comment]
Not tired yet running around various issue trackers and posting same things again that are totally irrelevant to development and take valuable developer's time?

**Comment by Neustradamus** [comment]
It is for have good softwares and easy to update when we know the XEP supported versions :)
