### ISSUE TITLE
How to search in contacts?

### ISSUE THREAD

**Issue by vickyjain05** [redsolution/xabber-web#12]
I know these is an option to search when you click the left hand side contacts icon, but the one which we see on the main screen is something that also needs search bar
![xabber web](https://user-images.githubusercontent.com/15120330/37698634-be14dc8a-2d09-11e8-9a36-21ee9840ef86.png)

**Comment by andrewnenakhov** [comment]
Search in contacts is implemented in contacts tab (icon below group chat icon). Right popup contacs bar wasn't meant to be permanent element for contacts manipulation. Of course, you can add search bar there too, but we're not sure if we want it in Xabber for Web.
