### ISSUE TITLE
Reloading history in a chat window

### ISSUE THREAD

**Issue by vickyjain05** [redsolution/xabber-web#13]
Sometimes when I am chatting from a different mobile client and web client simultaneously, some chats are missed in both the clients, can we have a button called Reload History in the chat options that simply will reload the last few chats
![xabber web 1](https://user-images.githubusercontent.com/15120330/37698757-50948196-2d0a-11e8-8a9a-4010aca3ad9a.png)

**Comment by andrewnenakhov** [comment]
We do not experience lost chats. There are some issues when browser is sleeping, we intend to fix that. But if all is well, chats shouldn't be lost, and this button is not necessary. Also, user can always reload all browser tab.
