### ISSUE TITLE
How to search within chats

### ISSUE THREAD

**Issue by vickyjain05** [redsolution/xabber-web#14]
Current Search bar just searches on basis of names of users, can we also extend this functionality to search within chats as well?
![xabber web 2](https://user-images.githubusercontent.com/15120330/37698867-cb4df5a2-2d0a-11e8-981d-145ea9134181.png)

**Comment by andrewnenakhov** [comment]
To make proper chat history search we need some server to support chat search first. Without that client would have to do download all chat history to device first, and with such ephemeral thing as a browser tab it's not a good solution. So chat history search would have to wait until we get some server support for it.
