### ISSUE TITLE
Can we have keyboard shortcuts for emoticons

### ISSUE THREAD

**Issue by vickyjain05** [redsolution/xabber-web#15]
The list is available here: https://usefulshortcuts.com/msn-messenger/smiley-faces-winks.php
![uknowva messenger 6](https://user-images.githubusercontent.com/15120330/38086850-92b9f0d2-3373-11e8-95d4-17672a44af52.png)

**Comment by andrewnenakhov** [comment]
It is wrong to replace smileys (text structured to look like faces, :) or :( ) with emoticons ( 😀😂 ). Xabber supports emojii keyboard, if person wants to send emoticon it can do so, but users should not be forced to send emojii instead if text files if they want it so
