### ISSUE TITLE
Issue with browser slowing down in xabber for web when i have more than 300 contacts

### ISSUE THREAD

**Issue by vickyjain05** [redsolution/xabber-web#19]
Please check attached screenshot
![slowing-down-xabber](https://user-images.githubusercontent.com/15120330/39911819-51f6e3de-551a-11e8-9131-b5c5d9d35d22.png)

**Comment by andrewnenakhov** [comment]
What's that browser you are using?

**Comment by vickyjain05** [comment]
Mozilla Firefox: 59.0.3 (64-bit)

**Comment by andrewnenakhov** [comment]
Process can't be optimized to run in background, because XMPP is rather data-intensive protocol and can't be simplified without losing much functionality. However server might be optimized to load history much more efficiently than it is done now by polling roster, but that requires server updates. We're working on it, but don't expect great results soon. It's complicated.

**Comment by vickyjain05** [comment]
Can we not cache it in the localstorage of the browser? Like u r caching the image, etc at the moment...This will reduce a lot of overhead on the server too.

We can make the cache expire in say 30 days...let me know ur thoughts :)

**Comment by andrewnenakhov** [comment]
No, that would be a bad idea. We plan to make Xabber dump all unused data from memory, it'd too require some updates on server. We're working on it, but don't expect too quick results

**Comment by nzidan** [comment]
> No, that would be a bad idea. We plan to make Xabber dump all unused data from memory, it'd too require some updates on server. We're working on it, but don't expect too quick results

Hi @andrewnenakhov,
do you have any update for the issue?

**Comment by andrewnenakhov** [comment]
@nzidan actually, yes, Xabber for Web works much more efficiently with recently released Xabber server that has support for our work-in-progress XEPs. We're not completely done yet, though.
