### ISSUE TITLE
Can group chat not visible after I come back after a while

### ISSUE THREAD

**Issue by vickyjain05** [redsolution/xabber-web#22]
The same is available in mobile app, I sent a text from the app and then it was visible in web

**Comment by andrewnenakhov** [comment]
Could you please explain in more details what's exactly wrong?

**Comment by vickyjain05** [comment]
Let me explain

When in a group, I can simply see it in my recents chats list, but when I go offline, it is not visible after i come back, I can see it only when someone else pings on the group or i ping from the mobile app in the same group.

Basically group chats are not persistent like we have in whatsapp, etc. It should always be there in the list.

**Comment by andrewnenakhov** [comment]
that's because we currently don't have means to load recent chats effectively. The only option is to go through the roster and fetch most recent history entry from server history, this takes time. We plan to create a more efficient method to load latest conversations on reconnect in the future, but that's not an issue with group chats per se, more of a common XMPP problem (one of the most serious ones). Stay tuned.

**Comment by vickyjain05** [comment]
I understand, may be we can keep another database table for this and map all users with their corresponding group jabber ids here, at least we will be able to show them in the list, we need not go through the roster and fetch most recents....it will save time and resources.

That's my thought, you might have a better idea though...

**Comment by andrewnenakhov** [comment]
That's in a nutshell is exactly what we plan to do, but since we're at it we also plan to have metadata to accompany conversations, like read/delivery markers and unread message counters - clients can't reliably count it if they don't download all message history.

**Comment by andrewnenakhov** [comment]
@patelprisha could you please explain what exactly do you mean by "group list which i have created on my xmpp platform" ?

**Comment by andrewnenakhov** [comment]
What do you call 'your xmpp platform' ? Currently, group chats can only be created on domain xmppdev01.xabber.com and are loaded after some while after browser tab is refreshed. Are you talking about these group chats or some others?

**Comment by vickyjain05** [comment]
mine is hosted on chat.uknowva.com

**Comment by patelprisha** [comment]
@andrewnenakhov 
My xmpp platform is hosted on our server with ejjabberd. Roster contacts are loaded completely fine but i could not find the groups (conference room) which i have created.

Is there a way to get those on group list?

**Comment by andrewnenakhov** [comment]
@patelprisha currently group chats are hardcoded in Xabber for Web to be hosted only on  xmppdev01.xabber.com host. Any other place is not currently supported. You'll need to install Xabber Server (which is not yet released as a software product!) on your host and configure client to use that host for your group chats.

**Comment by patelprisha** [comment]
You mean i can't load groups with my own ejjabberd domain right?

**Comment by panpansh** [comment]
is it done voluntarily ? are we limited by this open source version ? because actually I can not access group conferences

**Comment by andrewnenakhov** [comment]
Group chats are a new standard that is under development and can be 'hosted' only on servers that support it. There are several test servers where they can work, all are hosted by us. 

The client can be on any server, so you can create a group chat on (for example) **xmppdev01.xabber.com** server using your jabber.ru or xmpp.ru or xmpp.jp account. It is specifically designed that way to provide interoperability with any existing server even if it does not support new standard.

**Comment by nzidan** [comment]
> Group chats are a new standard that is under development and can be 'hosted' only on servers that support it. There are several test servers where they can work, all are hosted by us.
> 
> The client can be on any server, so you can create a group chat on (for example) **xmppdev01.xabber.com** server using your jabber.ru or xmpp.ru or xmpp.jp account. It is specifically designed that way to provide interoperability with any existing server even if it does not support new standard.

Hi @andrewnenakhov,
any update regarding Group chat

**Comment by andrewnenakhov** [comment]
@nzidan well it's mostly working! you can install Xabber Server and create group chats with Xabber for Web right now! (still, we're changing some things from time to time, but it is relatively minor)

 iOS version of Xabber is coming really soon, it too has nice support for group chats. We're waiting till Apple processes our developer account, and planning to publish it once it is ready.

**Comment by jamaisx** [comment]
xabber-web Still not working with Openfire, while Android version shows and connects to Openfire rooms

**Comment by andrewnenakhov** [comment]
@jamaisx "openfire rooms" are old MUC standard which is supproted by Xabber for Android because it was added years ago. We'll remove that in future updates.

**Comment by vandana-cdot** [comment]
Hi @andrewnenakhov 
We are using ejabberd server ,  group chat is running fine with android and ios app . Now we are working with xabber web we can see all roster contacts are loaded fine but  group (conference room) names and chats are not displayed . Are we missing something?

**Comment by andrewnenakhov** [comment]
@vandana-cdot Xabber for Web  does not support conferences (XEP-0045 MUC), and will not support it in the future. Use our far superior group chats instead.

**Comment by vandana-cdot** [comment]
HI @andrewnenakhov ,
Whats is this group chats then ? which XEP is related to Group chat . Group chat Icon I can see in xabber-web but which data it will support here?
Thanks in advance .

**Comment by andrewnenakhov** [comment]
@Vandana-MilesToGo check XEP-GROUPS here https://www.xabber.com/protocol/

It's in a bit not fully formal state currenlty but works for us as a reference documentation. This XEP is not recognized by the XSF, and we don't think that current XSF with their 'all is fine, we have all the pieces we need' attitude will recognize it anytime soon. But we are not concerned about that.
