### ISSUE TITLE
Docker file

### ISSUE THREAD

**Issue by petrk94** [redsolution/xabber-web#27]
Hello,

I would like to run xabber-web as web client. 
I have already a openfire xmpp server, but I could not find the correct instructions to run xabber on my VPS.
Kindly I would check out a docker-compose file, if you provide.

Thanks

**Comment by oxoWrk** [comment]
[Wiki](https://github.com/redsolution/xabber-web/wiki#install-and-setup-xabber-for-web)

**Comment by andrewnenakhov** [comment]
@petrk94 please read the link @oxoWrk provided. Requirements paragraph clearly states:

> Xabber for Web works in a browser and can interact with other services only with HTTP protocol. Because of this client requires a proxy service. Xabber for Web can work with BOSH Connection manager included with most XMPP servers. However, in this case Xabber for Web won't be able to work with other XMPP servers.
> 
> To circumvent this constraint we've developed Xabber Websocket Server - standalone web-server that allows web client to establish connection with any XMPP server.

You can deploy your own instance of Xabber Websocket Server, and you should supply Xabber for Web with it's URL.

**Comment by petrk94** [comment]
Ah I see.
Thanks
