### ISSUE TITLE
Uncaught TypeError: Cannot read property 'resolve' of undefined

### ISSUE THREAD

**Issue by devendrawebdeveloper** [redsolution/xabber-web#29]
I am loading chat(Xabber web) from ajax in website. It is working fine first time (See image first.png).
![firsttime](https://user-images.githubusercontent.com/4918366/56921972-c0213400-6ae4-11e9-8f4c-4fd67a9f9564.png)
But after second time it showing issue. (See image nexttime.png)
![nexttime](https://user-images.githubusercontent.com/4918366/56921974-c0b9ca80-6ae4-11e9-87e4-d675d1390839.png)

**Comment by oxoWrk** [comment]
maybe the problem is in your code

**Comment by andrewnenakhov** [comment]
@devendrawebdeveloper Xabber for Web that is being developed by us does not look like your screenshots. Probably you're having issues with your modifications.
