### ISSUE TITLE
Setting the developer environment. Authorization does not work - authentication error.

### ISSUE THREAD

**Issue by kaners80** [redsolution/xabber-web#30]
Loved your jabber-web.
I wanted to make a few changes to the design of the web page, it did not work out.

Operating system: Ubuntu-server 18.04

$ sudo apt install nodejs
$ node -v
v8.10.0

$ sudo apt install npm

$ git clone https://github.com/redsolution/xabber-web
$ cd xabber-web

Changed the CONNECTION_URL line: '', in the example_dev.html and example_index.html files:
on CONNECTION_URL: 'wss: //ws.xabber.com/websocket',

Established dependencies
$ make deps-install

Launched web development server:
$ make httpserver

Login successful
http://localhost:8000/example_**index**.html
Authorization is an error at:
http://localhost:8000/example_**dev**.html

If you run make minify and try to log in again at http://localhost:8000/example_index.html - Authorization Error.
In the browser console, the error is Invalid token.

I tried releases 1.0.15, 1.0.14, 1.0.13, 1.0.10

**Comment by valeria-gh** [comment]
You should run version from branch feature/group chats
