### ISSUE TITLE
How to create a chat group ?

### ISSUE THREAD

**Issue by MarcVJ** [redsolution/xabber-web#31]
Hello, I would like to create a private chat group in Xabber (both Web and Mobile) to talk to several friends at once, but I can't find how to do so. Is that possible in the current state of xabber-web ? How should I do ?

I would like to use Xabber to completely replace another well-known proprietary solution, and chat group creation seems to be the only thing missing. 

Thank you very much for your help !

**Comment by andrewnenakhov** [comment]
@MarcVJ group chats can currently only be created on our server xmppdev01.xabber.com (specify this in 'Create group chat' dialog. This group chat is an upcoming software implementing our new group chat protocol developed by us. Our reference documentation is here https://www.xabber.com/protocol/ but for the time being its not yet final (95+% done) and in Russian. 

Once we're done making server we'll release it, and we'll  start translating the documentation into English.

**Comment by MarcVJ** [comment]
@andrewnenakhov Alright, thank you very much for your quick answer !
