### ISSUE TITLE
Connect xabber-web to ejabberd  xmpp server on localhost

### ISSUE THREAD

**Issue by karmac2015** [redsolution/xabber-web#34]
I want to use xabber-web with ejabberd xmpp server (installed on my own server), can you tell me how can I set the value of CONNECTION_URL. I tried 'ws://SERVER_IP:5280/websocket but it doesn't work as expected.

**Comment by Sternstein** [comment]
Hello, could you provide information about your ejabberd version, index.html for xabber web and your ejabberd config file?

**Comment by karmac2015** [comment]
I installed ejabberd 19.09 on windows 7

index.html: 

```
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Xabber Web</title>
    <meta charset="utf-8">
    <link rel="shortcut icon" type="image/png" href="images/favicon.png"/>
    <link rel="manifest" href="manifest.json">
    <script src="https://www.gstatic.com/firebasejs/4.3.1/firebase.js"></script>
    <script src="https://www.gstatic.com/firebasejs/4.3.1/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/4.3.1/firebase-messaging.js"></script>
    <link rel="stylesheet" href="dist/xabber.min.css?v2.0.2">
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <script src="dist/xabber.min.js?v2.0.2"></script>
    <script>
        require(['xabber'], function (xabber) {
            xabber.configure({
                // Please specify location of xabber-websocket service,
                // e.g. 'wss://web.xabber.com/websocket
                // To run your own server visit https://github.com/redsolution/xabber-websocket
                CONNECTION_URL: 'ws://10.1.1.5:5280/ws',
                LOG_LEVEL: 'NONE'
            });
            xabber.start();
        });
    </script>
</head>

<body>
</body>

</html>
```

ejabberd config file:

`###
###'           ejabberd configuration file
###
### The parameters used in this configuration file are explained at
###
###       https://docs.ejabberd.im/admin/configuration
###
### The configuration file is written in YAML.
### *******************************************************
### *******           !!! WARNING !!!               *******
### *******     YAML IS INDENTATION SENSITIVE       *******
### ******* MAKE SURE YOU INDENT SECTIONS CORRECTLY *******
### *******************************************************
### Refer to http://en.wikipedia.org/wiki/YAML for the brief description.
###

hosts:
  - "10.1.1.5"

loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100

certfiles:
  - "C:/ProgramData/ejabberd/conf/server.pem"
##  - "/etc/letsencrypt/live/localhost/fullchain.pem"
##  - "/etc/letsencrypt/live/localhost/privkey.pem"

ca_file: "C:/ProgramData/ejabberd/conf/cacert.pem"

listen:
  -
    port: 5222
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5269
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
  -
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
  -
    port: 1883
    module: mod_mqtt
    backlog: 1000

s2s_use_starttls: optional

acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
  admin:
    user:
      - "admin@10.1.1.5"

access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: loopback
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: loopback
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number

shaper:
  normal: 1000
  fast: 50000

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast

max_fsm_queue: 10000

acme:
   contact: "mailto:admin@10.1.1.5"
   ca_url: "https://acme-v01.api.letsencrypt.org"

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    ## db_type: sql
    assume_mam_usage: true
    default: never
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      mam: false
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      ## Avoid buggy clients to make their bookmarks public
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ## Only accept registration requests from the "trusted"
    ## network (see access_rules section above).
    ## Think twice before enabling registration from any
    ## address. See the Jabber SPAM Manifesto for details:
    ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false

### Local Variables:
### mode: yaml
### End:
### vim: set filetype=yaml tabstop=8
`

**Comment by Sternstein** [comment]
You need to modify your ejabberd config - add "/ws": ejabberd_http_ws to another listener. You put it on port 5443, but you tried to use it on port 5280.

It should be like
  -
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws

**Comment by karmac2015** [comment]
I set CONNECTION_URL to 'ws://10.1.1.5:5443/ws' but the following errors appear in the console:

![Untitled](https://user-images.githubusercontent.com/13750094/70991925-3654c400-20d1-11ea-9cdc-53c947828508.png)

**Comment by Sternstein** [comment]
Use it without tls - just on port 5280.

**Comment by karmac2015** [comment]
Thank you, it works.
But I have now a problem with uploading file

`xabber.min.js?v2.0.2:32 OPTIONS https://10.1.1.5:5443/upload/75d73cc24b619109b855320116fbdfc3216cf7c9/MknNj06ZKNEZg79uKmfHHETJStYvPSEcSt3xA6p0/flag.png net::ERR_CERT_AUTHORITY_INVALID`

**Comment by karmac2015** [comment]
Please can you tell me how can I use web socket ws with tls enabled ?

**Comment by andrewnenakhov** [comment]
Probably you have to install a security certificate and make your system trust it.
