### ISSUE TITLE
how to make an voice call or video call

### ISSUE THREAD

**Issue by swbus** [redsolution/xabber-web#38]
greate projects!
but anyone can tell me, how make a voice call or video call?
my xmpp server is openfire-4.5.1

**Comment by andrewnenakhov** [comment]
There is a call icon at the top of a chat block, to the left from search and archive icons.

**Comment by swbus** [comment]
Yes, I found these two buttons, but after pressing it, there is no prompt at the other end. Do I need to configure openfire specifically?

**Comment by swbus** [comment]
Another problem, I can only use http to connect to xabber-websocket, enter https://127.0.0.1:8080/client, nothing happens

**Comment by swbus** [comment]
what should I do?

**Comment by swbus** [comment]
Thanks for your quick reply

**Comment by andrewnenakhov** [comment]
Create a separate issue pls. Also, you do you have a websocket server running on your local PC (127.0.0.1)? (if you didn't set it up, you don't have one running)

**Comment by swbus** [comment]
yes, I run xabber-websocket
