### ISSUE TITLE
Missing Xabber .SVG logo

### ISSUE THREAD

**Issue by Neustradamus** [redsolution/xabber-web#40]
I do not found the Xabber .SVG logo, where it is?

Thanks in advance.

**Comment by Neustradamus** [comment]
@a-iv, @andrewnenakhov: Where is it?

Thanks in advance.

**Comment by andrewnenakhov** [comment]
[Xabber Logo.svg.zip](https://github.com/redsolution/xabber-web/files/4842986/Xabber.Logo.svg.zip)
