### ISSUE TITLE
Chat Markers issue

### ISSUE THREAD

**Issue by anyuta1166** [redsolution/xabber-web#45]
Hello. I'm here again with ejabberd and Conversations.

I've found an issue with Chat Markers in **2.1.0**.

- Messages are never marked as "Read".

- Messages sometimes are not marked as "Delivered".
Namely, messages sent from Conversations to Conversations and carbon-copied to Xabber Web are marked as "Delivered". Messages sent from Xabber Web to Conversations stays in "Sent" status despite being actually delivered.

The point is that it worked fine in **2.0.2**. Messages were getting marked as "Delivered" when they were delivered and thay also were getting marked as "Read" when they were actually read by user.

Did you break this feature or switched to a proprietary protocol?

**Comment by andrewnenakhov** [comment]
@anyuta1166 we have (partially) dropped support for XEP-0184: Message Delivery Receipts, in favor of XEP-0333 that does everything 0184 does and then some more, which makes 0184 obsolete.

Our policy towards obsolete extensions is that we _sometimes_ accept incoming data from legacy clients, but we never propagate such extensions. For example, Xabber clients will display vCard avatars, but will never set such avatar, publishing in using XEP-0084 instead (not that this XEP does not have issues, but so far we tolerate them). 

In your case, Xabber accepts markers when they are exchanged between third-party clients and are carbon copied to Xabber. But outgoing messages sent by Xabber do not request delivery notification and remote client does not send it. 

To fix your issue you may ask the other developer to add support for XEP-0333. Regarding you mentioning a 'proprietary' protocol, we actually DID extend 0333 in a non-breaking way with a more strict requirement to provide server stanza IDs in receipts. (the lack of  mandatory message IDs is the grave congenital defect of an XMPP protocol, which makes it notoriously hard to fix in a non-breaking way).
