### ISSUE TITLE
Update Xabber Web

### ISSUE THREAD

**Issue by urmatej** [redsolution/xabber-web#48]
hello,

I have a strange error lately using xabber-web.
When I log in, it asks me, if I should update to ne version, but that never succeeds.

> Update Xabber Web
> New version 2.1.0 (1) is available. 
>  Reload page to fetch this changes?

I tried clearing all my history, started login from scratch, but this still pops up.

Any ideas?

I'm using xabber on android and through web.

Best,
Matej

**Comment by valeria-gh** [comment]
Thanks, it's fixed.
