### ISSUE TITLE
Повысить автономность Веб-клиента

### ISSUE THREAD

**Issue by ELForcer** [redsolution/xabber-web#51]
Здравствуйте.
Имеется свой Jabber-сервер и установленный рядом Xabber-web. 
При заблокированных DNS клиент не работает, поскольку не может загрузить скрипты из сети Интернет.
![Снимок экрана от 2020-12-24 13-29-53](https://user-images.githubusercontent.com/30798063/103078943-5b391c80-45ec-11eb-9608-646a740021c5.png)

Для повышения автономности клиента, просьба отвязать от веб-скриптов, положив их локальную папку и обращаться к ним.

2. По умолчанию клиент пытается подключиться к xabber.com. Я немного подправил код, что бы можно было обращаться к собственному серверу

```

<html lang="en">
<head>
    <title>Xabber Web</title>
    <meta charset="utf-8">
    <link rel="shortcut icon" type="image/png" href="images/favicon.png"/>
    <link rel="manifest" href="manifest.json">
    <script src="https://www.gstatic.com/firebasejs/4.3.1/firebase.js"></script>
    <script src="https://www.gstatic.com/firebasejs/4.3.1/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/4.3.1/firebase-messaging.js"></script>
    <link rel="stylesheet" href="dist/xabber.min.css?v2.1.0">
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <script src="dist/xabber.min.js?v2.1.0"></script>
    <script src="custom.js"></script>
    <script>
        var result = getGet();
        var ip= result['ip'];

        if (ip!= 'undefined')
        {
        document.cookie = "ip="+ip;
        }
        require(['xabber'], function (xabber) {
            xabber.configure({
                // Please specify location of xabber-websocket service,
                // e.g. 'wss://web.xabber.com/websocket
                // To run your own server visit https://github.com/redsolution/xabber-websocket
                CONNECTION_URL: 'ws://'+GetCookie('ip')+':15281/xmpp',
                LOG_LEVEL: 'WARN'
            });
            xabber.start();
        });
    </script>
</head>

<body>
<div class="login-container"></div>
</body>
</html>
```
После этого, можно подключиться к серверу через URL-запрос: http://192.168.18.15/xabber/?ip=192.168.18.15
Просьба сделать в клиенте возможность указывать любой сервер без костылей.

3. При загрузке файла клиент пытается подключится к домену, который указывается в логине учетки (допустим username@domen.local), однако если машина не имеет домена, а домен у учетки просто формальность, то обмен файлами и голосовыми сообщениями не работают, поскольку он пытается подключится по несуществующему домену domen.local, а не по подключаемому IP. Просьба в клиенте сделать возможность указывать реальный адрес сервера, что бы можно было полноценно использовать клиент.

4. Неплохо бы сделать поддержку клиента и  на русском языке.

**Comment by andrewnenakhov** [comment]
Вообще, лучше отдельные тикеты создавать. По пунктам:

1.  вероятно, сделаем, это, и правда, не очень хорошо
2. предполагается, что это настраивается в конфиге (ну, htmlке!) в том месте, где выкладывается клиент. Мы же знаем куда хотим подключаться клиентом, расположенным у себя на хосте?
3. не совсем понятно. url для загрузки файла генерирует xmpp-сервер, и клиент туда и пытается загрузить файл. Лучше создайте отдельный тикет. Ну и , вообще, xmpp лучше не использовать без домена, лучше зарегистрироват свой и жить нормально. Вон, .cyou домены можно за полтора доллара в год иметь, и жить спокойно без всего этого.
4. с переводами придется подождать пока мы не осилим объединить базы терминов всех наших клиентов (iOS, Android, Web, потому что переводить их по-отдельности глупо - на 80% переводы совпадают), но сделать это не так просто и потребуется существенная организаторская работа, до которой пока руки не доходят. Планируем этим заняться, когда стабилизируются и синхронизируются все необходимые для жизни фичи

**Comment by ELForcer** [comment]
По 3-му пункту. Я рылся в коде и даже смог отвязать от домена, который генерирует xmpp-сервер и привязав его к cookie браузера, но после обновления с git, все правки потерялись. 
Я конечно понимаю что xmpp лучше не использовать без домена, но этот сервер работает уже 4  года без домена и обычный чат работает замечательно, но хочется вернуть возможность пересылки файлов.

**Comment by ELForcer** [comment]
По второму пункту. У нас Веб-клиент находится на стыке разных подсетей. Грубо говоря, каждый клиент попадет по своему адресу. Кто то под 10.0.0.12, кто по 172.16.30.24, кто то под  192.168.30.20, мы например попадаем под 192.168.18.15. Поэтому я сделал вот такой костыль.  IP-адреса разные, а вот сервер по факту один и тот же.

**Comment by andrewnenakhov** [comment]
> Я конечно понимаю что xmpp лучше не использовать без домена, но этот сервер работает уже 4 года без домена и обычный чат работает замечательно, но хочется вернуть возможность пересылки файлов.

Это настолько нетипичное использование джаббера, что нам вряд ли есть смысл этим заниматься. В конце-концов, можно сделать локальное доменное имя резолвящееся из Ваших подсетей, и всем клиентам использовать его из всех подсетей. 

> По второму пункту. У нас Веб-клиент находится на стыке разных подсетей. Грубо говоря, каждый клиент попадет по своему адресу. Кто то под 10.0.0.12, кто по 172.16.30.24, кто то под 192.168.30.20, мы например попадаем под 192.168.18.15. Поэтому я сделал вот такой костыль. IP-адреса разные, а вот сервер по факту один и тот же.

По-моему, надо просто правильно настроить IP-роутинг в этих сетях, и всем ходить на один и тот же адрес. Лучше, если этот адрес будет разрешаться через локальный DNS.

**Comment by ELForcer** [comment]
Подключение к серверу идет через туннелируемое соединение, к которому подключаются прокси-сервера которые видят клиенты, которые сидят в своих подсетях. Грубо говоря подключение происходит так Клиент А --> Прокси А--> Jabber+Xabber <-- Прокси Б <-- Клиент Б

**Comment by andrewnenakhov** [comment]
> Грубо говоря подключение происходит так Клиент А --> Прокси А--> Jabber+Xabber <-- Прокси Б <-- Клиент Б
А таких прокси больше 20 штук, за которым может быть от 1 до 100 клиентов..

Ну, значит, надо настроить правильно роутинг во всех этих сетях, вот и всё. Маршруты, если что, можно через dhcp раздавать.

**Comment by ELForcer** [comment]
Добрый день. После обновления до версии 2.3.2 заметил, что в example_index.html часть скриптов и css теперь хранятся локально, спасибо. Вопрос к следующему куску кода, который по-прежнему ссылается на внешку:
```
    <script src="https://www.gstatic.com/firebasejs/4.3.1/firebase.js"></script>
    <script src="https://www.gstatic.com/firebasejs/4.3.1/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/4.3.1/firebase-messaging.js"></script>

```
Насколько это нужные скрипты и будет ли корректно работать без этих скриптов? Спасибо.

**Comment by andrewnenakhov** [comment]
@ELForcer эти библиотеки необходимы для получения клиентом пуш-уведомлений. Как оно будет работать, если их просто закомментировать, мы не проверяли. Вероятно, можно собрать версию, где просто отключить весь код, связанный с пуш-уведомлениями, но мы этим пока заниматься не планируем. 

Самым простым способом повысить автономность будет выкачать эти библиотеки к себе на хост и указать локальный путь к ним.
