### ISSUE TITLE
Missing libsignal-protocol.js

### ISSUE THREAD

**Issue by f055** [redsolution/xabber-web#53]
The `index.html` is missing the `libsignal-protocol.js` library, and attempts to open the Xabber Web client in Safari or Firefox results in grey screen and an error in the web console saying `Error: Signal library required!`.

By downloading the missing .js file from `https://raw.githubusercontent.com/signalapp/libsignal-protocol-javascript/master/dist/libsignal-protocol.js` to `xabber_ws/lib/xabber_ws-0.3.1/priv/client/dist` and updating the `index.html` file with `<script src="dist/libsignal-protocol.js"></script>` the Xabber Web successfully starts.

**Comment by valeria-gh** [comment]
The libsignal-protocol.js is in the ./src/lib/ directrory. We added <script/> in example_index.html and example_dev.html. Thanks

**Comment by f055** [comment]
Thanks. I also had a similar issue using https://github.com/redsolution/xabber-websocket because the client used there in the `/priv` was also missing the `libsignal` in its `index.html`.
