### ISSUE TITLE
Add translation of one line wiki

### ISSUE THREAD

**Issue by iamsimakov** [redsolution/xabber-web#56]
https://github.com/redsolution/xabber-web/wiki#1-install-and-setup-xabber-websocket-server

> You need GNU make and git in your PATH. Также в системе должен быть предустановлен erlang (для Ubuntu - erlang или esl-erlang).

_You need GNU `make` and `git` in your PATH. Also you should install `erlang` package (or `esl-erlang`), maybe different for your system._

I would like to suppose my own translation but I could not find way to do it. Thanks

**Comment by oxoWrk** [comment]
done.
Thanks!
