### ISSUE TITLE
Availability web.xabber.com from Russia

### ISSUE THREAD

**Issue by iamsimakov** [redsolution/xabber-web#57]
web.xabber.com is not available from Russia.
For example, this is test from 2ip.ru 

![xabber_com](https://user-images.githubusercontent.com/11376039/107084740-7a8cb180-6808-11eb-89d3-49e2aa0b7854.png)

Сould you do something about it? Or check access from you

Now site is resolved as 188.226.175.57

**Comment by andrewnenakhov** [comment]
xabber.com, xabber.org and a number of subdomains are blocked by russian censorship agency RosKomNadzor for refusing to comply with regulations applied to 'organizers of dissemination of information'. To solve this problem we would probably need to remove Putin from power and dissolve RosKomNadzor. Right now I believe it would be rather difficult with our resources. 

Eventually we'll make a publically available web client on a different domain, but it'll likely be blocked, too.
