### ISSUE TITLE
how do i make a direct connection to my xmpp server

### ISSUE THREAD

**Issue by isachi2004** [redsolution/xabber-web#59]
am new to xmpp. how do i make a direct connection to my xmpp server like openfire wihout going through a proxy service.

**Comment by andrewnenakhov** [comment]
Browsers can't connect directly using xmpp protocol. You need a server with built-in websocket server, like [Xabber Server](https://github.com/redsolution/xabber-server/)

(also worth noting that web version of Xabber contains a lot of improvements over stock XMPP protocol that make it work so much better and faster than it is possible on stock XMPP servers - like OpenFire - so you should better use it with the server that supports all it's features in full)

**Comment by isachi2004** [comment]
on what platform do Xabber Server run on, that is windows, linux or etc

**Comment by isachi2004** [comment]
is it posible to run it on windows platform. sory am still new. if posible
give me pointers on what should learn to run your app.

**Comment by isachi2004** [comment]
When I try to execute $make run, am getting the attached error.
How do i workaround it. am new to linux. am on fedora. i have installed
erlang packages
