### ISSUE TITLE
Incoming and outgoing messages splitted into two discussions

### ISSUE THREAD

**Issue by oxpa** [redsolution/xabber-web#6]
Please, have a look at this screenshot:
![](http://i.imgur.com/NdeuWwN.png)
I have the only contact for vexer@jaber.ru. And seems like server stores the contact in lower:
```sql
select distinct(peer, bare_peer) from archive where username = 'oxpa' and peer ilike 'V.exeR%'; 
row 
--------------------------------------------- 
(v.exer@jabber.ru,v.exer@jabber.ru)
(v.exer@jabber.ru/Miranda,v.exer@jabber.ru) 
(2 rows) 
```
Still, I have all outgoing messages in the first entry (V.exeR) and all incoming messages in the second one (V.exeR@jabber.ru).
Feel free to ask additional questions as for now I can't say what causes this bug

**Comment by andrewnenakhov** [comment]
fixed quite a while ago
