### ISSUE TITLE
Blocked by CORS policy

### ISSUE THREAD

**Issue by lexcorp** [redsolution/xabber-web#60]
Access to XMLHttpRequest at 'https://mydomain.local:9091/' from origin 'https://mydomain.local' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by andrewnenakhov** [comment]
This is not a Xabber issue. The host you are trying to access has CORS policy that prohibits cross-origin requests. You should change CORS policy to allow such requests.
