### ISSUE TITLE
WebCrypto not found

### ISSUE THREAD

**Issue by ELForcer** [redsolution/xabber-web#61]
Добрый день. Обновился до версии 2.3.2.
Теперь в браузере выходит такая ошибка:

```
Uncaught Error: WebCrypto not found
    at libsignal-protocol.js:35204
    at libsignal-protocol.js:35324
    at libsignal-protocol.js:36542

```
![Снимок экрана от 2021-05-27 16-49-18](https://user-images.githubusercontent.com/30798063/119828722-83b2a300-bf0b-11eb-81e8-4efa5bfca24b.png)

Пробовал в Yandex.Browser и в Vivaldi.

**Comment by oxoWrk** [comment]
нужно добавить в индекс файл 
`<script src="./dist/libsignal-protocol.js"></script>` 
(смотри example_index.html)

**Comment by ELForcer** [comment]
Он там есть.

![image](https://user-images.githubusercontent.com/30798063/119830281-27e91980-bf0d-11eb-8024-b9fee7d894be.png)

**Comment by oxoWrk** [comment]
значит отсутсвует сам файл в папке .dist

**Comment by ELForcer** [comment]
Он там тоже есть

![image](https://user-images.githubusercontent.com/30798063/119830912-c37a8a00-bf0d-11eb-8a6a-aefca542894d.png)

**Comment by andrewnenakhov** [comment]
Возможно, в Яндекс Браузере и Вивальди не реализован WebCrypto API. Попробуйте воспользоваться нормальным браузером, например, Firefox.

**Comment by ELForcer** [comment]
Про ненормальность Я.Браузера и Вивальди щас обидно стало, но Mozilla FireFox пишет ту же ошибку.

![image](https://user-images.githubusercontent.com/30798063/119945393-73033b00-bfa6-11eb-9ada-60ba349c98b8.png)

**Comment by oxoWrk** [comment]
WebCrypto API блокируется на хостах без HTTPS

**Comment by ELForcer** [comment]
@oxoWrk вот это уже похоже на ответ. Спасибо.

**Comment by andrewnenakhov** [comment]
@ELForcer ну как предоставили релевантную информацию, так сразу и ответили. :-D 

Вообще, рекомендуем настроить всё стандартным образом: в открытом интернете с публичными адресами и нормальными сертификатами.

**Comment by ELForcer** [comment]
@andrewnenakhov, у  нас закрытый чат в корпоративной сети и уже работает по защищенным каналам связи. Сертификат просто лишний. Да и как видно он работает по IP, а не по домену.

**Comment by andrewnenakhov** [comment]
@ELForcer если вы используете джаббер в таком режиме, то вам, получается, вообще не нужны никакие его преимущества, типа федерируемости, так что куда как проще использовать какой-нибудь рокетчат или маттермост.
