### ISSUE TITLE
How to use/join group chats?

### ISSUE THREAD

**Issue by raptureveteran1** [redsolution/xabber-web#68]
I'm trying to use the base web.xabber.com and I can join my companies server but most of our work is done through groups which I have no earthly idea how to join. Searching doesn't bring up anything.

**Comment by andrewnenakhov** [comment]
hi. To join group chat from Xabber you should press +, then select 'create group'. Or just add group's XMPP id to add contact directly, if you have access you'll be allowed to join group. 

It would only work with servers that support our group chat protocol though.
