### ISSUE TITLE
XEP-0045: MUC features

### ISSUE THREAD

**Issue by 13husen** [redsolution/xabber-web#8]
hello,i think xabber-web is really great and has rich features,but it will be much greater if there's multi user chat or groupchat,because you know,it's the one of the most crucial features for chatapps,so,any future plan for it ?

**Comment by joshp23** [comment]
any news on this, muc would be awesome feature for web!

**Comment by antoniomorais360** [comment]
:( No answer yet, really?

**Comment by andrewnenakhov** [comment]
Xabber for Web has insanely great support for a new generation of group chat. It has nothing to do with MUCs though, because XEP-0045 is an irredeemable crap. We're in final stages of making it: everything works really great, just need some polishing.

**Comment by antoniomorais360** [comment]
That is awesome. How about to release an alpha version for any group-chat? I think, even with limitations, it is better then nothing. Do you have some deadline?

**Comment by nzidan** [comment]
Hi,
is there any update for MUC feature? are we expecting this soon?

**Comment by andrewnenakhov** [comment]
@nzidan actually it is already available, with Xabber Server. If you don't have your own server, just go to https://web.xabber.com/develop/ , login with your XMPP account, press +, select 'Create group chat' and provide 'xmppdev01.xabber.com' in 'custom server' field, as in the [picture](https://xmpp.redsolution.com/upload/4bddf4f264f5c6577f16551f16a0abdf3f7ff84d/wNWEoHJt/%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5.png) . Should work. 

But, this server is frequently updated, sometimes with breaking changes, so don't use it for production purposes.
